import { AutoGeneratedBlogResult, AutoBlogGenerateInput } from '../types/autoBlog';

export async function generateAutoBlog(
  input: AutoBlogGenerateInput
): Promise<AutoGeneratedBlogResult> {
  const res = await fetch('/api/admin/auto-blog-generator/generate', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    credentials: 'include',
    body: JSON.stringify(input),
  });

  const data = await res.json();

  if (res.ok && data && data.success && data.data) {
    return data.data;
  }

  throw new Error(data?.error || 'Failed to complete unified auto blog generation');
}
