import { Router } from 'express';
import healthRoutes from './health.routes';
import packageRoutes from './package.routes';
import serviceRoutes from './service.routes';
import authRoutes from './auth.routes';
import adminPackageRoutes from './admin-package.routes';
import founderRoutes from './founder.routes';
import officeRoutes from './office.routes';
import adminFounderRoutes from './admin-founder.routes';
import adminOfficeRoutes from './admin-office.routes';
import adminServiceCategoryRoutes from './admin-service-category.routes';
import adminServiceRoutes from './admin-service.routes';
import adminMediaRoutes from './admin-media.routes';
import leadRoutes from './lead.routes';
import adminLeadRoutes from './admin-lead.routes';
import testimonialRoutes from './testimonial.routes';
import adminTestimonialRoutes from './admin-testimonial.routes';
import blogRoutes from './blog.routes';
import adminBlogRoutes from './admin-blog.routes';
import settingsRoutes from './settings.routes';
import adminSettingsRoutes from './admin-settings.routes';
import clientLogoRoutes from './client-logo.routes';
import adminClientLogoRoutes from './admin-client-logo.routes';
import paymentRoutes from './payment.routes';

const apiRouter = Router();

// Mount sub-routes under /api
apiRouter.use('/', healthRoutes);
apiRouter.use('/auth', authRoutes);
apiRouter.use('/payment', paymentRoutes);
apiRouter.use('/packages', packageRoutes);
apiRouter.use('/services', serviceRoutes);
apiRouter.use('/testimonials', testimonialRoutes);
apiRouter.use('/blogs', blogRoutes);
apiRouter.use('/settings', settingsRoutes);
apiRouter.use('/client-logos', clientLogoRoutes);
apiRouter.use('/leads', leadRoutes);
apiRouter.use('/consultations', leadRoutes);
apiRouter.use('/admin/packages', adminPackageRoutes);
apiRouter.use('/admin/service-categories', adminServiceCategoryRoutes);
apiRouter.use('/admin/services', adminServiceRoutes);
apiRouter.use('/admin/leads', adminLeadRoutes);
apiRouter.use('/admin/testimonials', adminTestimonialRoutes);
apiRouter.use('/admin/blogs', adminBlogRoutes);
apiRouter.use('/admin/settings', adminSettingsRoutes);
apiRouter.use('/admin/client-logos', adminClientLogoRoutes);
apiRouter.use('/founder', founderRoutes);
apiRouter.use('/office', officeRoutes);
apiRouter.use('/admin/founder', adminFounderRoutes);
apiRouter.use('/admin/office', adminOfficeRoutes);
apiRouter.use('/admin', adminMediaRoutes);

export default apiRouter;
