import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  Loader2,
  CheckCircle2,
  AlertCircle,
  Copy,
  Check,
  FileText,
  Globe,
  Tag,
  HelpCircle,
  ArrowRight,
  RefreshCw,
  Send,
  ExternalLink,
  Layers,
} from 'lucide-react';
import { GeneratedBlogDraft } from '../../types/blog';
import { generateAiBlog, createBlogPost } from '../../services/blog.service';
import { SERVICES } from '../../data/websiteData';
import { RichContentRenderer } from '../blog/RichContentRenderer';

interface AdminAiBlogFactoryProps {
  onBlogSaved?: () => void;
  onOpenInEditor?: (draft: GeneratedBlogDraft) => void;
}

export const AdminAiBlogFactory: React.FC<AdminAiBlogFactoryProps> = ({
  onBlogSaved,
  onOpenInEditor,
}) => {
  // Input fields
  const [topic, setTopic] = useState('');
  const [targetService, setTargetService] = useState('');

  // Generation states
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSavingDraft, setIsSavingDraft] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);

  // Generated blog data
  const [generatedDraft, setGeneratedDraft] = useState<GeneratedBlogDraft | null>(null);

  // Active view tab for generated result
  const [activeTab, setActiveTab] = useState<'content' | 'seo' | 'faq' | 'raw'>('content');
  const [copiedField, setCopiedField] = useState<string | null>(null);

  // Quick prompt suggestions
  const QUICK_TOPICS = [
    'Private Limited vs LLP: Complete Comparison for Indian Startups',
    'Mandatory ROC Filings for Small Companies under Companies Act 2013',
    'How to Register a Trademark in India: Comprehensive Step-by-Step Guide',
    'GST Invoicing Rules and Mandatory E-Way Bill Thresholds Explained',
    'Startup India DPIIT Recognition: Eligibility, Tax Exemption & Benefits',
    'FSSAI Food License Renewal and Annual Statutory Compliance Guide',
  ];

  const handleGenerate = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!topic.trim()) {
      setError('Please enter a topic or primary keyword');
      return;
    }

    setIsGenerating(true);
    setError(null);
    setSuccessMessage(null);

    try {
      const draft = await generateAiBlog(topic.trim(), targetService);
      setGeneratedDraft(draft);
      setSuccessMessage('Article successfully generated by AI! Review below and save as draft.');
    } catch (err: any) {
      setError(err.message || 'Failed to generate AI blog article');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSaveAsDraft = async () => {
    if (!generatedDraft) return;

    setIsSavingDraft(true);
    setError(null);

    try {
      // Append FAQ to the blog content if present
      let finalContent = generatedDraft.blogContent;
      if (generatedDraft.faq && generatedDraft.faq.length > 0) {
        finalContent += '\n\n## Frequently Asked Questions (FAQs)\n\n';
        generatedDraft.faq.forEach((faqItem, idx) => {
          finalContent += `### Q${idx + 1}: ${faqItem.question}\n${faqItem.answer}\n\n`;
        });
      }

      await createBlogPost({
        title: generatedDraft.title,
        slug: generatedDraft.slug,
        category: generatedDraft.category || 'Company Registration',
        author: 'LEGOMARK Editorial Board',
        content: finalContent,
        excerpt: generatedDraft.summary,
        seoTitle: generatedDraft.seoTitle,
        metaDescription: generatedDraft.metaDescription,
        seoSlug: generatedDraft.slug,
        isPublished: false, // Save strictly as Draft
      });

      setSuccessMessage('Generated article saved as Draft in your Blogs catalog!');
      if (onBlogSaved) {
        onBlogSaved();
      }
    } catch (err: any) {
      setError(err.message || 'Failed to save generated draft');
    } finally {
      setIsSavingDraft(false);
    }
  };

  const handleCopyText = (textToCopy: string, fieldKey: string) => {
    navigator.clipboard.writeText(textToCopy);
    setCopiedField(fieldKey);
    setTimeout(() => setCopiedField(null), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Module Title Card */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 relative overflow-hidden">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2.5">
              <div className="w-9 h-9 rounded-xl bg-orange-500/10 border border-orange-500/20 flex items-center justify-center text-orange-400">
                <Sparkles className="w-5 h-5" />
              </div>
              <h2 className="text-xl font-bold text-white tracking-tight">AI Blog Factory</h2>
              <span className="px-2 py-0.5 text-xs font-semibold rounded-md bg-orange-500/10 text-orange-400 border border-orange-500/20">
                Gemini Powered
              </span>
            </div>
            <p className="text-sm text-slate-400 mt-2 max-w-2xl">
              Instantly draft authoritative legal, taxation, and corporate compliance articles with tailored SEO titles, meta descriptions, slugs, focus keywords, and FAQs formatted specifically for LEGOMARK INDIA.
            </p>
          </div>

          {generatedDraft && (
            <div className="flex items-center gap-2 shrink-0">
              <button
                type="button"
                onClick={handleSaveAsDraft}
                disabled={isSavingDraft || isGenerating}
                className="px-4 py-2.5 bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 text-white text-sm font-semibold rounded-xl shadow-md transition-all flex items-center gap-2"
              >
                {isSavingDraft ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <CheckCircle2 className="w-4 h-4" />
                )}
                <span>Save as Draft</span>
              </button>
            </div>
          )}
        </div>

        {/* Form Inputs */}
        <form onSubmit={handleGenerate} className="mt-6 pt-6 border-t border-slate-800/80 space-y-4">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-4">
            {/* Topic/Keyword Input */}
            <div className="lg:col-span-7">
              <label htmlFor="ai-topic-input" className="block text-xs font-semibold text-slate-300 mb-1.5">
                Topic / Primary Keyword *
              </label>
              <input
                id="ai-topic-input"
                type="text"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                placeholder="e.g. Private Limited Company Registration in India or GST Annual Return Form 9 Filing"
                className="w-full px-4 py-3 bg-slate-950 border border-slate-800 rounded-xl text-sm text-white placeholder-slate-500 focus:outline-hidden focus:border-orange-500 transition-colors"
                disabled={isGenerating}
              />
            </div>

            {/* Target Service Dropdown */}
            <div className="lg:col-span-5">
              <label htmlFor="ai-service-select" className="block text-xs font-semibold text-slate-300 mb-1.5">
                Target Service / Practice Area (Optional)
              </label>
              <select
                id="ai-service-select"
                value={targetService}
                onChange={(e) => setTargetService(e.target.value)}
                className="w-full px-4 py-3 bg-slate-950 border border-slate-800 rounded-xl text-sm text-white focus:outline-hidden focus:border-orange-500 transition-colors"
                disabled={isGenerating}
              >
                <option value="">General Corporate & Legal Advisory</option>
                {SERVICES.map((s) => (
                  <option key={s.id} value={s.title}>
                    {s.title} ({s.category})
                  </option>
                ))}
              </select>
            </div>
          </div>

          {/* Prompt suggestions pills */}
          <div>
            <div className="text-[11px] font-medium text-slate-400 mb-1.5 flex items-center gap-1.5">
              <span>Try popular advisory topics:</span>
            </div>
            <div className="flex flex-wrap gap-1.5">
              {QUICK_TOPICS.map((qt) => (
                <button
                  key={qt}
                  type="button"
                  onClick={() => setTopic(qt)}
                  className="px-2.5 py-1 text-xs rounded-lg bg-slate-800/80 hover:bg-slate-700/80 text-slate-300 hover:text-white border border-slate-700/60 transition-colors text-left"
                >
                  {qt}
                </button>
              ))}
            </div>
          </div>

          {/* Action Row */}
          <div className="flex items-center justify-end pt-2">
            <button
              type="submit"
              disabled={isGenerating || !topic.trim()}
              className="px-6 py-3 bg-orange-500 hover:bg-orange-600 disabled:opacity-50 text-white text-sm font-semibold rounded-xl shadow-lg hover:shadow-orange-500/20 transition-all flex items-center gap-2"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>Generating Complete Blog & SEO Metadata...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  <span>Generate Blog Article</span>
                </>
              )}
            </button>
          </div>
        </form>
      </div>

      {/* Notifications */}
      {successMessage && (
        <div className="p-4 rounded-xl bg-emerald-950/60 border border-emerald-800 text-emerald-300 text-sm flex items-center justify-between">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 shrink-0 text-emerald-400" />
            <span>{successMessage}</span>
          </div>
          <button onClick={() => setSuccessMessage(null)} className="text-emerald-400 hover:text-emerald-200">
            &times;
          </button>
        </div>
      )}

      {error && (
        <div className="p-4 rounded-xl bg-rose-950/60 border border-rose-800 text-rose-300 text-sm flex items-center justify-between">
          <div className="flex items-center gap-2">
            <AlertCircle className="w-4 h-4 shrink-0 text-rose-400" />
            <span>{error}</span>
          </div>
          <button onClick={() => setError(null)} className="text-rose-400 hover:text-rose-200">
            &times;
          </button>
        </div>
      )}

      {/* Loading Skeleton */}
      {isGenerating && (
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-8 text-center space-y-4">
          <div className="w-12 h-12 rounded-2xl bg-orange-500/10 border border-orange-500/20 text-orange-400 flex items-center justify-center mx-auto animate-pulse">
            <Sparkles className="w-6 h-6 animate-spin" />
          </div>
          <h3 className="text-lg font-bold text-white">Drafting Authoritative Legal Article</h3>
          <p className="text-sm text-slate-400 max-w-md mx-auto">
            Gemini is structuring statutory references, drafting procedural steps, crafting SEO metadata, and formulating FAQs for Indian founders...
          </p>
          <div className="flex justify-center gap-2 pt-2">
            <span className="w-2 h-2 rounded-full bg-orange-500 animate-ping"></span>
            <span className="w-2 h-2 rounded-full bg-orange-400 animate-pulse"></span>
            <span className="w-2 h-2 rounded-full bg-orange-300"></span>
          </div>
        </div>
      )}

      {/* GENERATED OUTPUT PREVIEW */}
      {generatedDraft && !isGenerating && (
        <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden shadow-xl">
          {/* Header Bar */}
          <div className="p-5 border-b border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-slate-900/90">
            <div>
              <div className="flex items-center gap-2">
                <span className="px-2.5 py-0.5 text-xs font-semibold rounded-md bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                  Ready to Review
                </span>
                <span className="px-2.5 py-0.5 text-xs font-semibold rounded-md bg-slate-800 text-slate-300 border border-slate-700">
                  {generatedDraft.category}
                </span>
              </div>
              <h3 className="text-lg font-bold text-white mt-1.5">
                {generatedDraft.title}
              </h3>
            </div>

            <div className="flex items-center gap-2">
              {onOpenInEditor && (
                <button
                  type="button"
                  onClick={() => onOpenInEditor(generatedDraft)}
                  className="px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold rounded-xl border border-slate-700 transition-colors flex items-center gap-1.5"
                >
                  <FileText className="w-3.5 h-3.5" />
                  <span>Open in Rich Editor</span>
                </button>
              )}
              <button
                type="button"
                onClick={handleSaveAsDraft}
                disabled={isSavingDraft}
                className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold rounded-xl transition-all shadow-md flex items-center gap-1.5"
              >
                {isSavingDraft ? (
                  <Loader2 className="w-3.5 h-3.5 animate-spin" />
                ) : (
                  <CheckCircle2 className="w-3.5 h-3.5" />
                )}
                <span>Save as Draft</span>
              </button>
            </div>
          </div>

          {/* Quick Stats & Keywords Ribbon */}
          <div className="px-6 py-3.5 bg-slate-950/60 border-b border-slate-800/80 flex flex-wrap items-center justify-between gap-3 text-xs">
            <div className="flex items-center gap-4 flex-wrap">
              <div>
                <span className="text-slate-500">Focus Keyword: </span>
                <span className="font-semibold text-orange-400">{generatedDraft.focusKeyword}</span>
              </div>
              <div>
                <span className="text-slate-500">Slug: </span>
                <span className="font-mono text-slate-300">/{generatedDraft.slug}</span>
              </div>
            </div>

            <div className="flex items-center gap-2 flex-wrap">
              <span className="text-slate-500">Related: </span>
              {generatedDraft.relatedKeywords?.map((kw, i) => (
                <span
                  key={i}
                  className="px-2 py-0.5 rounded-md bg-slate-800/80 text-slate-300 text-[11px] border border-slate-700/60"
                >
                  {kw}
                </span>
              ))}
            </div>
          </div>

          {/* View Tabs */}
          <div className="flex border-b border-slate-800 px-6 bg-slate-900/50">
            <button
              onClick={() => setActiveTab('content')}
              className={`py-3 px-4 text-xs font-semibold border-b-2 transition-colors flex items-center gap-2 ${
                activeTab === 'content'
                  ? 'border-orange-500 text-orange-400'
                  : 'border-transparent text-slate-400 hover:text-slate-200'
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              <span>Article Content</span>
            </button>
            <button
              onClick={() => setActiveTab('seo')}
              className={`py-3 px-4 text-xs font-semibold border-b-2 transition-colors flex items-center gap-2 ${
                activeTab === 'seo'
                  ? 'border-orange-500 text-orange-400'
                  : 'border-transparent text-slate-400 hover:text-slate-200'
              }`}
            >
              <Globe className="w-3.5 h-3.5" />
              <span>SEO & Meta Tags</span>
            </button>
            <button
              onClick={() => setActiveTab('faq')}
              className={`py-3 px-4 text-xs font-semibold border-b-2 transition-colors flex items-center gap-2 ${
                activeTab === 'faq'
                  ? 'border-orange-500 text-orange-400'
                  : 'border-transparent text-slate-400 hover:text-slate-200'
              }`}
            >
              <HelpCircle className="w-3.5 h-3.5" />
              <span>FAQ ({generatedDraft.faq?.length || 0})</span>
            </button>
            <button
              onClick={() => setActiveTab('raw')}
              className={`py-3 px-4 text-xs font-semibold border-b-2 transition-colors flex items-center gap-2 ${
                activeTab === 'raw'
                  ? 'border-orange-500 text-orange-400'
                  : 'border-transparent text-slate-400 hover:text-slate-200'
              }`}
            >
              <Tag className="w-3.5 h-3.5" />
              <span>Raw Markdown</span>
            </button>
          </div>

          {/* Tab Content Panels */}
          <div className="p-6">
            {/* 1. Article Content View */}
            {activeTab === 'content' && (
              <div className="space-y-6">
                {/* Summary Card */}
                <div className="p-4 rounded-xl bg-slate-950 border border-slate-800">
                  <div className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1 flex items-center justify-between">
                    <span>Summary / Excerpt</span>
                    <button
                      onClick={() => handleCopyText(generatedDraft.summary, 'summary')}
                      className="text-slate-400 hover:text-white flex items-center gap-1 text-[11px]"
                    >
                      {copiedField === 'summary' ? (
                        <Check className="w-3 h-3 text-emerald-400" />
                      ) : (
                        <Copy className="w-3 h-3" />
                      )}
                      <span>Copy</span>
                    </button>
                  </div>
                  <p className="text-sm text-slate-200 leading-relaxed">
                    {generatedDraft.summary}
                  </p>
                </div>

                {/* Rendered Blog Content */}
                <div className="p-6 rounded-xl bg-slate-950/80 border border-slate-800/80">
                  <RichContentRenderer content={generatedDraft.blogContent} />
                </div>
              </div>
            )}

            {/* 2. SEO & Meta Tags View */}
            {activeTab === 'seo' && (
              <div className="space-y-4">
                <div className="grid grid-cols-1 gap-4">
                  {/* Title */}
                  <div className="p-4 rounded-xl bg-slate-950 border border-slate-800">
                    <div className="flex items-center justify-between mb-1.5">
                      <span className="text-xs font-semibold text-slate-400">Title Tag</span>
                      <button
                        onClick={() => handleCopyText(generatedDraft.title, 'title')}
                        className="text-xs text-orange-400 hover:underline flex items-center gap-1"
                      >
                        {copiedField === 'title' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                        <span>Copy</span>
                      </button>
                    </div>
                    <p className="text-sm font-semibold text-white">{generatedDraft.title}</p>
                    <span className="text-[11px] text-slate-500 mt-1 block">
                      {generatedDraft.title.length} characters
                    </span>
                  </div>

                  {/* SEO Title */}
                  <div className="p-4 rounded-xl bg-slate-950 border border-slate-800">
                    <div className="flex items-center justify-between mb-1.5">
                      <span className="text-xs font-semibold text-slate-400">SEO Title (SERP)</span>
                      <button
                        onClick={() => handleCopyText(generatedDraft.seoTitle, 'seoTitle')}
                        className="text-xs text-orange-400 hover:underline flex items-center gap-1"
                      >
                        {copiedField === 'seoTitle' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                        <span>Copy</span>
                      </button>
                    </div>
                    <p className="text-sm font-medium text-emerald-400">{generatedDraft.seoTitle}</p>
                    <span className="text-[11px] text-slate-500 mt-1 block">
                      {generatedDraft.seoTitle.length} characters (Optimal: 50-60)
                    </span>
                  </div>

                  {/* Meta Description */}
                  <div className="p-4 rounded-xl bg-slate-950 border border-slate-800">
                    <div className="flex items-center justify-between mb-1.5">
                      <span className="text-xs font-semibold text-slate-400">Meta Description</span>
                      <button
                        onClick={() => handleCopyText(generatedDraft.metaDescription, 'metaDescription')}
                        className="text-xs text-orange-400 hover:underline flex items-center gap-1"
                      >
                        {copiedField === 'metaDescription' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                        <span>Copy</span>
                      </button>
                    </div>
                    <p className="text-sm text-slate-300 leading-relaxed">{generatedDraft.metaDescription}</p>
                    <span className="text-[11px] text-slate-500 mt-1 block">
                      {generatedDraft.metaDescription.length} characters (Optimal: 150-160)
                    </span>
                  </div>

                  {/* Slug */}
                  <div className="p-4 rounded-xl bg-slate-950 border border-slate-800">
                    <div className="flex items-center justify-between mb-1.5">
                      <span className="text-xs font-semibold text-slate-400">URL Slug</span>
                      <button
                        onClick={() => handleCopyText(generatedDraft.slug, 'slug')}
                        className="text-xs text-orange-400 hover:underline flex items-center gap-1"
                      >
                        {copiedField === 'slug' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                        <span>Copy</span>
                      </button>
                    </div>
                    <p className="text-sm font-mono text-orange-400">/{generatedDraft.slug}</p>
                  </div>

                  {/* Focus & Related Keywords */}
                  <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-3">
                    <div>
                      <span className="text-xs font-semibold text-slate-400 block mb-1">Primary Focus Keyword</span>
                      <span className="px-3 py-1 text-xs font-semibold rounded-lg bg-orange-500/10 text-orange-400 border border-orange-500/20">
                        {generatedDraft.focusKeyword}
                      </span>
                    </div>

                    <div>
                      <span className="text-xs font-semibold text-slate-400 block mb-1.5">Related LSI Keywords</span>
                      <div className="flex flex-wrap gap-2">
                        {generatedDraft.relatedKeywords?.map((kw, idx) => (
                          <span
                            key={idx}
                            className="px-2.5 py-1 text-xs rounded-lg bg-slate-900 border border-slate-700 text-slate-300"
                          >
                            {kw}
                          </span>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* 3. FAQ View */}
            {activeTab === 'faq' && (
              <div className="space-y-4">
                <div className="flex items-center justify-between pb-2 border-b border-slate-800">
                  <span className="text-xs font-semibold text-slate-400">
                    Statutory & Practical Frequently Asked Questions
                  </span>
                  <button
                    onClick={() => {
                      const text = generatedDraft.faq
                        .map((f, i) => `Q${i + 1}: ${f.question}\nA: ${f.answer}`)
                        .join('\n\n');
                      handleCopyText(text, 'allFaq');
                    }}
                    className="text-xs text-orange-400 hover:underline flex items-center gap-1"
                  >
                    {copiedField === 'allFaq' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                    <span>Copy All FAQs</span>
                  </button>
                </div>

                <div className="space-y-3">
                  {generatedDraft.faq?.map((faqItem, idx) => (
                    <div key={idx} className="p-4 rounded-xl bg-slate-950 border border-slate-800">
                      <h4 className="text-sm font-semibold text-white flex items-start gap-2">
                        <span className="text-orange-400 font-mono">Q{idx + 1}.</span>
                        <span>{faqItem.question}</span>
                      </h4>
                      <p className="text-xs text-slate-300 mt-2 leading-relaxed pl-6">
                        {faqItem.answer}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* 4. Raw Markdown View */}
            {activeTab === 'raw' && (
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold text-slate-400">
                    Raw Markdown Content ({generatedDraft.blogContent.length} chars)
                  </span>
                  <button
                    onClick={() => handleCopyText(generatedDraft.blogContent, 'rawContent')}
                    className="text-xs text-orange-400 hover:underline flex items-center gap-1"
                  >
                    {copiedField === 'rawContent' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                    <span>Copy Markdown</span>
                  </button>
                </div>
                <textarea
                  readOnly
                  rows={16}
                  value={generatedDraft.blogContent}
                  className="w-full p-4 bg-slate-950 border border-slate-800 rounded-xl font-mono text-xs text-slate-300 resize-none focus:outline-hidden"
                />
              </div>
            )}
          </div>

          {/* Footer Bar */}
          <div className="p-4 bg-slate-950 border-t border-slate-800 flex items-center justify-between">
            <span className="text-xs text-slate-500">
              Generated by LEGOMARK AI Blog Factory • Powered by Google Gemini 3.8 Flash
            </span>

            <button
              type="button"
              onClick={handleSaveAsDraft}
              disabled={isSavingDraft}
              className="px-5 py-2.5 bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 text-white text-xs font-bold rounded-xl shadow-md transition-all flex items-center gap-2"
            >
              {isSavingDraft ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <CheckCircle2 className="w-4 h-4" />
              )}
              <span>Save Generated Result as Draft</span>
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
