import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  RefreshCw,
  CheckCircle2,
  AlertCircle,
  FileText,
  Image as ImageIcon,
  HelpCircle,
  Link2,
  Gauge,
  Save,
  Globe,
  ArrowRight,
  Eye,
  Edit2,
  Copy,
  Check,
  Tag,
  Clock,
  Layers,
  Info,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  BookOpen,
} from 'lucide-react';
import { fetchPublicServices, ClientPublicServiceSummary } from '../../services/publicService.service';
import { createBlogPost } from '../../services/blog.service';
import { generateAutoBlog } from '../../services/autoBlog.service';
import { AutoGeneratedBlogResult } from '../../types/autoBlog';
import { RichTextEditor } from './RichTextEditor';
import { AdminNavSection } from './AdminSidebar';

interface AdminAutoBlogGeneratorProps {
  onNavigateSection?: (section: AdminNavSection) => void;
}

export const AdminAutoBlogGenerator: React.FC<AdminAutoBlogGeneratorProps> = ({
  onNavigateSection,
}) => {
  // Input Form State
  const [topic, setTopic] = useState('');
  const [selectedServiceSlug, setSelectedServiceSlug] = useState('');
  const [services, setServices] = useState<ClientPublicServiceSummary[]>([]);
  const [isLoadingServices, setIsLoadingServices] = useState(true);

  // Workflow Execution State
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationStep, setGenerationStep] = useState<number>(0);
  const [error, setError] = useState<string | null>(null);

  // Review & Draft State
  const [result, setResult] = useState<AutoGeneratedBlogResult | null>(null);
  const [activeReviewTab, setActiveReviewTab] = useState<'content' | 'links' | 'seo'>('content');
  const [copiedId, setCopiedId] = useState<string | null>(null);

  // Editable Draft Form Data (Allows admin review and edits before saving)
  const [draftForm, setDraftForm] = useState<{
    title: string;
    seoTitle: string;
    metaDescription: string;
    slug: string;
    category: string;
    focusKeyword: string;
    relatedKeywords: string[];
    content: string;
    excerpt: string;
    featuredImage: string;
    faqs: Array<{ question: string; answer: string }>;
  }>({
    title: '',
    seoTitle: '',
    metaDescription: '',
    slug: '',
    category: 'Company Registration',
    focusKeyword: '',
    relatedKeywords: [],
    content: '',
    excerpt: '',
    featuredImage: '',
    faqs: [],
  });

  // Save / Publish State
  const [isSaving, setIsSaving] = useState(false);
  const [saveSuccessMessage, setSaveSuccessMessage] = useState<string | null>(null);
  const [saveError, setSaveError] = useState<string | null>(null);

  // Load active services dynamically on mount (NEVER hardcoded)
  useEffect(() => {
    loadServices();
  }, []);

  const loadServices = async () => {
    setIsLoadingServices(true);
    try {
      const activeList = await fetchPublicServices();
      setServices(activeList || []);
      if (activeList && activeList.length > 0) {
        setSelectedServiceSlug(activeList[0].slug);
      }
    } catch (err) {
      console.warn('Could not load services dynamically in AutoBlogGenerator', err);
    } finally {
      setIsLoadingServices(false);
    }
  };

  // Step names for visual progress indicator
  const workflowSteps = [
    '1. Keyword Research & Intent Mapping',
    '2. Authoritative Blog Content Generation',
    '3. Custom 16:9 Featured Image Generation',
    '4. Structured FAQs & PAA Generation',
    '5. Relevant Internal Link Suggestions',
    '6. LEGOMARK SEO Analysis & Scoring',
  ];

  // Run the unified 6-step workflow
  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!topic.trim()) {
      setError('Please enter a blog topic or seed idea.');
      return;
    }
    if (!selectedServiceSlug) {
      setError('Please select a target service.');
      return;
    }

    setIsGenerating(true);
    setError(null);
    setSaveSuccessMessage(null);
    setSaveError(null);
    setGenerationStep(1);

    // Simulated progress tick for smoother multi-step feedback while waiting for orchestration
    const stepInterval = setInterval(() => {
      setGenerationStep((prev) => (prev < 6 ? prev + 1 : prev));
    }, 2800);

    try {
      const targetServiceObj = services.find((s) => s.slug === selectedServiceSlug);
      const targetServiceName = targetServiceObj ? targetServiceObj.title : selectedServiceSlug;

      const generated = await generateAutoBlog({
        topic: topic.trim(),
        targetService: targetServiceName,
      });

      clearInterval(stepInterval);
      setGenerationStep(6);
      setResult(generated);

      // Populate editable draft state
      setDraftForm({
        title: generated.draft.title,
        seoTitle: generated.draft.seoTitle,
        metaDescription: generated.draft.metaDescription,
        slug: generated.draft.slug,
        category: generated.draft.category,
        focusKeyword: generated.draft.focusKeyword,
        relatedKeywords: generated.draft.relatedKeywords || [],
        content: generated.draft.content,
        excerpt: generated.draft.excerpt,
        featuredImage: generated.draft.featuredImage || '',
        faqs: generated.draft.faqs || [],
      });
    } catch (err: any) {
      clearInterval(stepInterval);
      setError(err.message || 'Auto Blog Generation failed. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  // Explicit Save / Publish Handler (NO auto-save or auto-publish)
  const handleSaveArticle = async (isPublished: boolean) => {
    setIsSaving(true);
    setSaveError(null);
    setSaveSuccessMessage(null);

    try {
      await createBlogPost({
        title: draftForm.title.trim(),
        slug: draftForm.slug.trim(),
        category: draftForm.category.trim(),
        content: draftForm.content,
        excerpt: draftForm.excerpt.trim(),
        featuredImage: draftForm.featuredImage || undefined,
        seoTitle: draftForm.seoTitle.trim(),
        metaDescription: draftForm.metaDescription.trim(),
        seoSlug: draftForm.slug.trim(),
        isPublished,
      });

      setSaveSuccessMessage(
        isPublished
          ? 'Article successfully published to live website!'
          : 'Article successfully saved as draft in Blogs & Articles.'
      );
    } catch (err: any) {
      setSaveError(err.message || 'Failed to save blog post');
    } finally {
      setIsSaving(false);
    }
  };

  const handleCopy = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  return (
    <div className="space-y-6 animate-fadeIn pb-16">
      {/* Top Banner */}
      <div className="bg-gradient-to-r from-slate-900 via-[#0D1527] to-slate-900 border border-slate-800 rounded-2xl p-6 relative overflow-hidden shadow-xl">
        <div className="absolute top-0 right-0 w-96 h-96 bg-orange-500/5 rounded-full blur-3xl pointer-events-none" />

        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 relative z-10">
          <div className="space-y-1.5">
            <div className="flex items-center gap-2.5">
              <div className="p-2 rounded-xl bg-orange-500/10 border border-orange-500/20 text-orange-400">
                <Sparkles className="w-5 h-5" />
              </div>
              <h1 className="text-xl sm:text-2xl font-bold text-white tracking-tight">
                Auto Blog Generator
              </h1>
              <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-orange-500/20 text-orange-300 border border-orange-500/30">
                Unified AI Workflow
              </span>
            </div>
            <p className="text-xs sm:text-sm text-slate-300 max-w-3xl leading-relaxed">
              One unified workflow orchestrating <strong className="text-white">Keyword Research</strong>,{' '}
              <strong className="text-white">Content Drafting</strong>,{' '}
              <strong className="text-white">Featured Image</strong>,{' '}
              <strong className="text-white">FAQs</strong>,{' '}
              <strong className="text-white">Internal Link Suggestions</strong>, and{' '}
              <strong className="text-white">LEGOMARK SEO Scoring</strong> in a single sequence.
            </p>
          </div>

          {onNavigateSection && (
            <button
              onClick={() => onNavigateSection('blogs')}
              className="px-3.5 py-2 text-xs font-semibold text-slate-300 hover:text-white bg-slate-800/80 hover:bg-slate-800 border border-slate-700/80 rounded-xl transition flex items-center gap-2 shrink-0 cursor-pointer"
            >
              <BookOpen className="w-4 h-4 text-slate-400" />
              <span>All Articles</span>
            </button>
          )}
        </div>
      </div>

      {/* INPUT FORM: Topic & Dynamic Service Selection */}
      <div className="bg-[#0B132B] border border-slate-800/90 rounded-2xl p-5 sm:p-6 shadow-xl space-y-4">
        <form onSubmit={handleGenerate} className="space-y-4">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-4">
            {/* Topic Input */}
            <div className="lg:col-span-7 space-y-1.5">
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-300">
                Blog Topic or Title Concept <span className="text-orange-400">*</span>
              </label>
              <input
                type="text"
                required
                disabled={isGenerating}
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                placeholder="e.g., Mandatory Annual Compliances for Private Limited Companies in India"
                className="w-full px-3.5 py-2.5 bg-[#070D1E] border border-slate-700/80 rounded-xl text-xs sm:text-sm text-white placeholder-slate-500 focus:outline-hidden focus:border-orange-500 transition"
              />
            </div>

            {/* Dynamic Target Service Selection */}
            <div className="lg:col-span-5 space-y-1.5">
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-300">
                Target Practice Area / Service <span className="text-orange-400">*</span>
              </label>
              <select
                required
                disabled={isGenerating || isLoadingServices}
                value={selectedServiceSlug}
                onChange={(e) => setSelectedServiceSlug(e.target.value)}
                className="w-full px-3.5 py-2.5 bg-[#070D1E] border border-slate-700/80 rounded-xl text-xs sm:text-sm text-white focus:outline-hidden focus:border-orange-500 transition font-medium"
              >
                {isLoadingServices ? (
                  <option value="">Loading active services...</option>
                ) : services.length === 0 ? (
                  <option value="">No active services found</option>
                ) : (
                  services.map((s) => (
                    <option key={s.id} value={s.slug}>
                      {s.title} ({s.category})
                    </option>
                  ))
                )}
              </select>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pt-2 border-t border-slate-800/80">
            <div className="text-xs text-slate-400 flex items-center gap-1.5">
              <Info className="w-3.5 h-3.5 text-slate-500 shrink-0" />
              <span>
                Active services loaded dynamically from PostgreSQL ({services.length} available). Never auto-publishes.
              </span>
            </div>

            <button
              type="submit"
              disabled={isGenerating || !topic.trim()}
              className="px-6 py-2.5 bg-orange-600 hover:bg-orange-500 active:bg-orange-700 disabled:opacity-50 text-white font-bold text-xs sm:text-sm rounded-xl transition shadow-lg shadow-orange-600/20 flex items-center justify-center gap-2 cursor-pointer shrink-0"
            >
              {isGenerating ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin text-white" />
                  <span>Executing AI Workflow...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 text-orange-200" />
                  <span>Generate Blog</span>
                </>
              )}
            </button>
          </div>
        </form>

        {/* WORKFLOW PROGRESS STEPPER (Displayed while generating) */}
        {isGenerating && (
          <div className="mt-4 p-5 rounded-xl bg-[#070D1E] border border-slate-800 space-y-3 animate-fadeIn">
            <div className="flex items-center justify-between text-xs">
              <span className="font-bold text-orange-400 flex items-center gap-2">
                <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                <span>Running Auto Blog Engines ({generationStep}/6)</span>
              </span>
              <span className="text-slate-400 font-mono">
                {Math.round((generationStep / 6) * 100)}% Completed
              </span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2 text-xs">
              {workflowSteps.map((stepLabel, idx) => {
                const isDone = generationStep > idx + 1;
                const isCurrent = generationStep === idx + 1;
                return (
                  <div
                    key={idx}
                    className={`p-2.5 rounded-lg border flex items-center gap-2 transition ${
                      isDone
                        ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300'
                        : isCurrent
                        ? 'border-orange-500/40 bg-orange-500/10 text-orange-300 animate-pulse'
                        : 'border-slate-800 bg-slate-900/40 text-slate-500'
                    }`}
                  >
                    {isDone ? (
                      <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                    ) : isCurrent ? (
                      <RefreshCw className="w-4 h-4 animate-spin text-orange-400 shrink-0" />
                    ) : (
                      <div className="w-4 h-4 rounded-full border border-slate-600 shrink-0" />
                    )}
                    <span className="text-[11px] font-medium truncate">{stepLabel}</span>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {error && (
          <div className="p-3.5 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-300 text-xs flex items-center gap-2">
            <AlertCircle className="w-4 h-4 text-rose-400 shrink-0" />
            <span>{error}</span>
          </div>
        )}
      </div>

      {/* RESULT & REVIEWABLE DRAFT WORKSPACE */}
      {result && (
        <div className="space-y-6 animate-fadeIn">
          {/* Action & Review Banner */}
          <div className="bg-[#0B132B] border border-slate-800/90 rounded-2xl p-5 shadow-xl flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div className="space-y-1">
              <div className="flex items-center gap-2">
                <span className="px-2.5 py-0.5 rounded-md text-xs font-bold uppercase bg-emerald-500/20 text-emerald-400 border border-emerald-500/30">
                  Ready for Editorial Review
                </span>
                <span className="text-xs text-slate-400">
                  Target Service:{' '}
                  <strong className="text-white">{result.targetService.title}</strong>
                </span>
              </div>
              <p className="text-xs text-slate-300">
                Inspect and refine the generated draft below. This article will not appear on your website until you explicitly choose to save or publish it.
              </p>
            </div>

            {/* Save / Publish Action Buttons */}
            <div className="flex items-center gap-2.5 shrink-0">
              <button
                type="button"
                onClick={() => handleSaveArticle(false)}
                disabled={isSaving}
                className="px-4 py-2.5 bg-slate-800 hover:bg-slate-700 text-slate-200 hover:text-white text-xs font-semibold rounded-xl border border-slate-700 transition flex items-center gap-2 cursor-pointer"
              >
                {isSaving ? (
                  <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                ) : (
                  <Save className="w-3.5 h-3.5 text-slate-400" />
                )}
                <span>Save as Draft</span>
              </button>

              <button
                type="button"
                onClick={() => handleSaveArticle(true)}
                disabled={isSaving}
                className="px-5 py-2.5 bg-orange-600 hover:bg-orange-500 text-white text-xs font-bold rounded-xl transition flex items-center gap-2 cursor-pointer shadow-lg shadow-orange-600/20"
              >
                {isSaving ? (
                  <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                ) : (
                  <Globe className="w-3.5 h-3.5" />
                )}
                <span>Publish to Website</span>
              </button>
            </div>
          </div>

          {/* Success or Error Notifications for Saving */}
          {saveSuccessMessage && (
            <div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 text-xs sm:text-sm flex items-center gap-2 shadow-lg">
              <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
              <span>{saveSuccessMessage}</span>
            </div>
          )}

          {saveError && (
            <div className="p-4 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-300 text-xs sm:text-sm flex items-center gap-2 shadow-lg">
              <AlertCircle className="w-4 h-4 text-rose-400 shrink-0" />
              <span>{saveError}</span>
            </div>
          )}

          {/* QUICK SUMMARY SCORECARD */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3.5">
            {/* Score */}
            <div className="bg-[#0B132B] border border-slate-800/90 rounded-xl p-4">
              <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1">
                <Gauge className="w-3.5 h-3.5 text-orange-400" />
                LEGOMARK SEO Score
              </p>
              <div className="flex items-baseline gap-1.5 mt-1">
                <span className="text-2xl font-bold text-emerald-400">
                  {result.seoAudit.legomarkScore}
                </span>
                <span className="text-xs text-slate-400">/ 100</span>
                <span className="text-[11px] font-semibold text-emerald-400 bg-emerald-500/10 px-1.5 py-0.2 rounded ml-1">
                  {result.seoAudit.scoreGrade}
                </span>
              </div>
            </div>

            {/* Keyword */}
            <div className="bg-[#0B132B] border border-slate-800/90 rounded-xl p-4">
              <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1">
                <Tag className="w-3.5 h-3.5 text-orange-400" />
                Focus Keyword
              </p>
              <p className="text-sm font-bold text-white mt-1 truncate">
                "{draftForm.focusKeyword}"
              </p>
              <p className="text-[11px] text-slate-500 mt-0.5">
                {result.keywordResearch.searchIntent} intent
              </p>
            </div>

            {/* Word Count */}
            <div className="bg-[#0B132B] border border-slate-800/90 rounded-xl p-4">
              <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1">
                <FileText className="w-3.5 h-3.5 text-orange-400" />
                Content Length
              </p>
              <p className="text-2xl font-bold text-white mt-1">
                {result.seoAudit.metrics?.wordCount || draftForm.content.split(/\s+/).length}
              </p>
              <p className="text-[11px] text-slate-500 mt-0.5">
                ~{result.seoAudit.metrics?.readingTimeMinutes || 4} min read
              </p>
            </div>

            {/* Internal Links */}
            <div className="bg-[#0B132B] border border-slate-800/90 rounded-xl p-4">
              <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1">
                <Link2 className="w-3.5 h-3.5 text-orange-400" />
                Internal Link Suggestions
              </p>
              <p className="text-2xl font-bold text-orange-400 mt-1">
                {result.internalLinkSuggestions.length}
              </p>
              <p className="text-[11px] text-slate-500 mt-0.5">
                Service & blog pathways
              </p>
            </div>
          </div>

          {/* REVIEW NAVIGATION TABS */}
          <div className="flex items-center gap-2 border-b border-slate-800 pb-px">
            <button
              onClick={() => setActiveReviewTab('content')}
              className={`px-4 py-2.5 text-xs sm:text-sm font-semibold rounded-t-xl transition flex items-center gap-2 border-b-2 cursor-pointer ${
                activeReviewTab === 'content'
                  ? 'border-orange-500 text-orange-400 bg-slate-900/60'
                  : 'border-transparent text-slate-400 hover:text-slate-200'
              }`}
            >
              <FileText className="w-4 h-4" />
              <span>Draft Content & Metadata</span>
            </button>

            <button
              onClick={() => setActiveReviewTab('links')}
              className={`px-4 py-2.5 text-xs sm:text-sm font-semibold rounded-t-xl transition flex items-center gap-2 border-b-2 cursor-pointer ${
                activeReviewTab === 'links'
                  ? 'border-orange-500 text-orange-400 bg-slate-900/60'
                  : 'border-transparent text-slate-400 hover:text-slate-200'
              }`}
            >
              <Link2 className="w-4 h-4" />
              <span>Internal Link Suggestions ({result.internalLinkSuggestions.length})</span>
            </button>

            <button
              onClick={() => setActiveReviewTab('seo')}
              className={`px-4 py-2.5 text-xs sm:text-sm font-semibold rounded-t-xl transition flex items-center gap-2 border-b-2 cursor-pointer ${
                activeReviewTab === 'seo'
                  ? 'border-orange-500 text-orange-400 bg-slate-900/60'
                  : 'border-transparent text-slate-400 hover:text-slate-200'
              }`}
            >
              <Gauge className="w-4 h-4" />
              <span>SEO Audit & Recommendations ({result.seoAudit.recommendations.length})</span>
            </button>
          </div>

          {/* TAB 1: DRAFT CONTENT & METADATA */}
          {activeReviewTab === 'content' && (
            <div className="space-y-6">
              {/* Core Metadata Fields */}
              <div className="bg-[#0B132B] border border-slate-800/90 rounded-2xl p-5 sm:p-6 space-y-4">
                <div className="text-xs font-bold uppercase tracking-wider text-orange-400">
                  Article Title & Search Engine Metadata
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="md:col-span-2">
                    <label className="block text-xs font-semibold text-slate-300 mb-1.5">
                      Article Title
                    </label>
                    <input
                      type="text"
                      value={draftForm.title}
                      onChange={(e) => setDraftForm({ ...draftForm, title: e.target.value })}
                      className="w-full px-3.5 py-2.5 bg-[#070D1E] border border-slate-700 rounded-xl text-sm text-white focus:outline-hidden focus:border-orange-500 font-medium"
                    />
                  </div>

                  <div>
                    <div className="flex items-center justify-between mb-1.5">
                      <label className="text-xs font-semibold text-slate-300">
                        SEO Title Tag
                      </label>
                      <span className="text-[11px] text-slate-400 font-mono">
                        {draftForm.seoTitle.length} / 60 chars
                      </span>
                    </div>
                    <input
                      type="text"
                      value={draftForm.seoTitle}
                      onChange={(e) => setDraftForm({ ...draftForm, seoTitle: e.target.value })}
                      className="w-full px-3.5 py-2.5 bg-[#070D1E] border border-slate-700 rounded-xl text-sm text-white focus:outline-hidden focus:border-orange-500"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-slate-300 mb-1.5">
                      URL Slug
                    </label>
                    <input
                      type="text"
                      value={draftForm.slug}
                      onChange={(e) => setDraftForm({ ...draftForm, slug: e.target.value })}
                      className="w-full px-3.5 py-2.5 bg-[#070D1E] border border-slate-700 rounded-xl text-sm text-white font-mono focus:outline-hidden focus:border-orange-500"
                    />
                  </div>

                  <div className="md:col-span-2">
                    <div className="flex items-center justify-between mb-1.5">
                      <label className="text-xs font-semibold text-slate-300">
                        Meta Description
                      </label>
                      <span className="text-[11px] text-slate-400 font-mono">
                        {draftForm.metaDescription.length} / 160 chars
                      </span>
                    </div>
                    <textarea
                      rows={2}
                      value={draftForm.metaDescription}
                      onChange={(e) =>
                        setDraftForm({ ...draftForm, metaDescription: e.target.value })
                      }
                      className="w-full px-3.5 py-2 bg-[#070D1E] border border-slate-700 rounded-xl text-xs sm:text-sm text-white focus:outline-hidden focus:border-orange-500 resize-none"
                    />
                  </div>
                </div>

                {/* Focus & Related Keywords */}
                <div className="pt-3 border-t border-slate-800/80 space-y-2">
                  <div className="text-xs font-semibold text-slate-400">
                    Focus & Semantic LSI Keywords
                  </div>
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="px-2.5 py-1 rounded-lg text-xs font-bold bg-orange-500/20 text-orange-300 border border-orange-500/30">
                      Primary: "{draftForm.focusKeyword}"
                    </span>
                    {draftForm.relatedKeywords.map((kw, i) => (
                      <span
                        key={i}
                        className="px-2.5 py-1 rounded-lg text-xs font-medium bg-slate-800 text-slate-300 border border-slate-700"
                      >
                        {kw}
                      </span>
                    ))}
                  </div>
                </div>
              </div>

              {/* Featured Image Review Card */}
              {draftForm.featuredImage && (
                <div className="bg-[#0B132B] border border-slate-800/90 rounded-2xl p-5 space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold uppercase tracking-wider text-orange-400 flex items-center gap-1.5">
                      <ImageIcon className="w-4 h-4" />
                      Generated 16:9 Featured Banner
                    </span>
                    <button
                      onClick={() => handleCopy(draftForm.featuredImage, 'featImg')}
                      className="text-xs text-slate-400 hover:text-white flex items-center gap-1 transition"
                    >
                      {copiedId === 'featImg' ? (
                        <>
                          <Check className="w-3.5 h-3.5 text-emerald-400" />
                          <span className="text-emerald-400 font-semibold">URL Copied</span>
                        </>
                      ) : (
                        <>
                          <Copy className="w-3.5 h-3.5" />
                          <span>Copy Image URL</span>
                        </>
                      )}
                    </button>
                  </div>

                  <div className="w-full max-w-2xl h-56 sm:h-72 rounded-xl overflow-hidden bg-slate-950 border border-slate-800">
                    <img
                      src={draftForm.featuredImage}
                      alt={draftForm.title}
                      className="w-full h-full object-cover"
                    />
                  </div>
                </div>
              )}

              {/* Body Content Editor */}
              <div className="bg-[#0B132B] border border-slate-800/90 rounded-2xl p-5 sm:p-6 space-y-3">
                <div className="flex items-center justify-between">
                  <label className="text-xs font-bold uppercase tracking-wider text-orange-400 flex items-center gap-1.5">
                    <Edit2 className="w-4 h-4" />
                    Article Body Content (Rich Text)
                  </label>
                  <span className="text-xs text-slate-400 font-mono">
                    {draftForm.content.split(/\s+/).length} words
                  </span>
                </div>

                <RichTextEditor
                  value={draftForm.content}
                  onChange={(val) => setDraftForm({ ...draftForm, content: val })}
                  minHeight="420px"
                />
              </div>

              {/* FAQs Review */}
              {draftForm.faqs.length > 0 && (
                <div className="bg-[#0B132B] border border-slate-800/90 rounded-2xl p-5 sm:p-6 space-y-3">
                  <div className="text-xs font-bold uppercase tracking-wider text-orange-400 flex items-center gap-1.5">
                    <HelpCircle className="w-4 h-4" />
                    Structured FAQs ({draftForm.faqs.length} Questions)
                  </div>

                  <div className="space-y-2.5">
                    {draftForm.faqs.map((faq, idx) => (
                      <div
                        key={idx}
                        className="p-3.5 rounded-xl bg-[#070D1E] border border-slate-800 space-y-1.5"
                      >
                        <h5 className="text-xs font-bold text-white flex items-center gap-2">
                          <span className="text-orange-400 font-mono">Q{idx + 1}:</span>
                          <span>{faq.question}</span>
                        </h5>
                        <p className="text-xs text-slate-300 leading-relaxed pl-6">
                          {faq.answer}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* TAB 2: INTERNAL LINK SUGGESTIONS */}
          {activeReviewTab === 'links' && (
            <div className="space-y-4">
              <div className="bg-[#0B132B] border border-slate-800/90 rounded-2xl p-5 shadow-lg space-y-1">
                <h4 className="text-sm font-bold text-white flex items-center gap-2">
                  <Link2 className="w-4 h-4 text-orange-400" />
                  <span>Strategic Internal Link Opportunities</span>
                </h4>
                <p className="text-xs text-slate-400">
                  These contextual pathways connect this article directly with your target commercial service and related corporate compliance guides.
                </p>
              </div>

              <div className="space-y-3">
                {result.internalLinkSuggestions.map((link, idx) => (
                  <div
                    key={idx}
                    className="bg-[#0B132B] border border-slate-800 rounded-2xl p-5 space-y-3 shadow-md"
                  >
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                      <div className="flex items-center gap-2">
                        <span
                          className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase ${
                            link.targetType === 'service'
                              ? 'bg-purple-500/20 text-purple-300 border border-purple-500/30'
                              : 'bg-blue-500/20 text-blue-300 border border-blue-500/30'
                          }`}
                        >
                          Target: {link.targetType}
                        </span>
                        <h5 className="text-sm font-bold text-white">{link.targetTitle}</h5>
                      </div>

                      <button
                        onClick={() =>
                          handleCopy(`[${link.anchorText}](${link.targetUrl})`, `link-${idx}`)
                        }
                        className="px-2.5 py-1 text-xs rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 flex items-center gap-1.5 transition shrink-0"
                      >
                        {copiedId === `link-${idx}` ? (
                          <>
                            <Check className="w-3.5 h-3.5 text-emerald-400" />
                            <span className="text-emerald-400 font-semibold">Copied Markdown</span>
                          </>
                        ) : (
                          <>
                            <Copy className="w-3.5 h-3.5" />
                            <span>Copy Link Snippet</span>
                          </>
                        )}
                      </button>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
                      <div className="p-3 rounded-xl bg-[#070D1E] border border-slate-800 space-y-1">
                        <span className="font-semibold text-orange-400">Recommended Anchor Text:</span>
                        <p className="text-white font-bold">"{link.anchorText}"</p>
                        <p className="text-[11px] text-slate-500 font-mono">{link.targetUrl}</p>
                      </div>

                      <div className="p-3 rounded-xl bg-[#070D1E] border border-slate-800 space-y-1">
                        <span className="font-semibold text-slate-400">Contextual Integration:</span>
                        <p className="text-slate-300 leading-relaxed text-xs">
                          {link.contextSnippet}
                        </p>
                      </div>
                    </div>

                    <div className="text-xs text-slate-400 flex items-start gap-1.5">
                      <Info className="w-3.5 h-3.5 text-slate-500 shrink-0 mt-0.5" />
                      <span>
                        <strong className="text-slate-300">Rationale:</strong> {link.reason}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* TAB 3: SEO AUDIT & RECOMMENDATIONS */}
          {activeReviewTab === 'seo' && (
            <div className="space-y-4">
              <div className="bg-[#0B132B] border border-slate-800/90 rounded-2xl p-5 shadow-lg space-y-1">
                <h4 className="text-sm font-bold text-white flex items-center gap-2">
                  <Gauge className="w-4 h-4 text-orange-400" />
                  <span>On-Page SEO Diagnostics & Recommendations</span>
                </h4>
                <p className="text-xs text-slate-400">
                  Evaluated across title tags, meta descriptions, semantic density, headings, and readability.
                </p>
              </div>

              {/* Recommendations List */}
              <div className="space-y-3">
                {result.seoAudit.recommendations.map((rec: any, idx: number) => (
                  <div
                    key={idx}
                    className="bg-[#0B132B] border border-slate-800 rounded-2xl p-4 sm:p-5 space-y-2 shadow-md"
                  >
                    <div className="flex items-center gap-2">
                      <span
                        className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase ${
                          rec.priority === 'high'
                            ? 'bg-rose-500/20 text-rose-400 border border-rose-500/30'
                            : rec.priority === 'medium'
                            ? 'bg-amber-500/20 text-amber-400 border border-amber-500/30'
                            : 'bg-blue-500/20 text-blue-400 border border-blue-500/30'
                        }`}
                      >
                        {rec.priority} Priority
                      </span>
                      <span className="text-xs font-semibold text-slate-400">{rec.dimension}</span>
                    </div>

                    <h5 className="text-sm font-bold text-white">{rec.title}</h5>
                    <p className="text-xs text-slate-300 leading-relaxed">{rec.description}</p>

                    <div className="text-xs text-slate-400 pt-1">
                      <strong className="text-slate-300">Suggested Action: </strong>
                      <span>{rec.suggestedAction}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
