export interface AutoBlogInternalLinkSuggestion {
  targetTitle: string;
  targetUrl: string;
  targetType: 'service' | 'blog';
  anchorText: string;
  contextSnippet: string;
  reason: string;
}

export interface AutoGeneratedBlogResult {
  topic: string;
  targetService: {
    id: string;
    title: string;
    slug: string;
    category: string;
  };
  keywordResearch: {
    primaryKeyword: string;
    competition: string;
    searchIntent: string;
    secondaryKeywords: string[];
    longTailKeywords: string[];
  };
  draft: {
    title: string;
    seoTitle: string;
    metaDescription: string;
    slug: string;
    category: string;
    author: string;
    focusKeyword: string;
    relatedKeywords: string[];
    content: string;
    excerpt: string;
    featuredImage: string | null;
    faqs: Array<{ question: string; answer: string }>;
    isPublished: boolean;
  };
  internalLinkSuggestions: AutoBlogInternalLinkSuggestion[];
  seoAudit: {
    legomarkScore: number;
    scoreGrade: string;
    dimensions: any;
    recommendations: any[];
    metrics: any;
  };
  generatedAt: string;
}

export interface AutoBlogGenerateInput {
  topic: string;
  targetService: string;
}
