import { keywordClusterService, KeywordClusterData } from './keyword-cluster.service';
import { aiBlogService, GeneratedBlogDraft } from './ai-blog.service';
import { internalLinkingService } from './internal-linking.service';
import { seoOptimizerService, SeoAnalysisResult } from './seo-optimizer.service';
import { serviceRepository } from '../repositories/service.repository';
import { logger } from '../utils/logger';

export interface AutoBlogInput {
  topic: string;
  targetService: string;
}

export interface AutoBlogInternalLinkSuggestion {
  targetTitle: string;
  targetUrl: string;
  targetType: 'service' | 'blog';
  anchorText: string;
  contextSnippet: string;
  reason: string;
}

export interface AutoGeneratedBlogResult {
  topic: string;
  targetService: {
    id: string;
    title: string;
    slug: string;
    category: string;
  };
  keywordResearch: {
    primaryKeyword: string;
    competition: string;
    searchIntent: string;
    secondaryKeywords: string[];
    longTailKeywords: string[];
  };
  draft: {
    title: string;
    seoTitle: string;
    metaDescription: string;
    slug: string;
    category: string;
    author: string;
    focusKeyword: string;
    relatedKeywords: string[];
    content: string;
    excerpt: string;
    featuredImage: string | null;
    faqs: Array<{ question: string; answer: string }>;
    isPublished: boolean;
  };
  internalLinkSuggestions: AutoBlogInternalLinkSuggestion[];
  seoAudit: {
    legomarkScore: number;
    scoreGrade: string;
    dimensions: any;
    recommendations: any[];
    metrics: any;
  };
  generatedAt: string;
}

export class AutoBlogGeneratorService {
  /**
   * Orchestrates the 6 existing AI engines in sequence:
   * 1. Keyword research (keywordClusterService)
   * 2. Blog content generation (aiBlogService.generateBlog)
   * 3. Featured image generation (aiBlogService.generateFeaturedImage)
   * 4. FAQ generation (aiBlogService.generateFaqs or draft.faq)
   * 5. Relevant internal-link suggestions (internalLinkingService + dynamic services)
   * 6. SEO analysis (seoOptimizerService.analyzeBlog)
   */
  async generateAutoBlog(input: AutoBlogInput): Promise<AutoGeneratedBlogResult> {
    const cleanTopic = input.topic?.trim();
    const cleanTargetService = input.targetService?.trim();

    if (!cleanTopic) {
      throw new Error('Blog Topic is required');
    }

    if (!cleanTargetService) {
      throw new Error('Target Service is required');
    }

    logger.info(
      `Starting Unified Auto Blog Generation for topic: "${cleanTopic}" with target service: "${cleanTargetService}"`,
      'AutoBlogGenerator'
    );

    // 0. Dynamically fetch active services from PostgreSQL repository (NEVER hardcoded)
    let activeServices: any[] = [];
    try {
      activeServices = await serviceRepository.getAllPublicServices();
    } catch (err) {
      logger.warn('Could not load services from DB in AutoBlogGenerator', 'AutoBlogGenerator', err);
    }

    // Match selected service or build fallback object
    const matchedService =
      activeServices.find(
        (s) =>
          s.slug === cleanTargetService ||
          s.title.toLowerCase() === cleanTargetService.toLowerCase() ||
          s.id === cleanTargetService
      ) ||
      activeServices[0] || {
        id: 'service-target',
        title: cleanTargetService,
        slug: cleanTargetService.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
        category: 'Corporate Advisory',
      };

    const targetServiceTitle = matchedService.title || cleanTargetService;

    // STEP 1: Keyword Research
    logger.info('Step 1/6: Running Keyword Research Engine...', 'AutoBlogGenerator');
    let cluster: KeywordClusterData;
    try {
      cluster = await keywordClusterService.generateCluster(cleanTopic, targetServiceTitle);
    } catch (err: any) {
      logger.warn('Keyword cluster generation warning, using fallback', 'AutoBlogGenerator', err);
      cluster = {
        topic: cleanTopic,
        targetService: targetServiceTitle,
        searchIntent: {
          primaryIntent: 'Commercial / Informational',
          explanation: 'Entrepreneurs researching statutory compliance and legal procedures in India.',
          targetAudience: 'Founders, Directors, and Compliance Officers',
        },
        primaryKeyword: {
          keyword: cleanTopic.split(/\s+/).slice(0, 4).join(' '),
          estimatedCompetition: 'Medium',
          rationale: 'Primary search topic query',
        },
        secondaryKeywords: [
          { keyword: `${targetServiceTitle} in India`, relevance: 'High' },
          { keyword: `${cleanTopic} legal process`, relevance: 'High' },
        ],
        longTailKeywords: [
          { keyword: `how to apply for ${targetServiceTitle} online`, userQueryContext: 'Procedural guidance' },
        ],
        questionKeywords: [],
      };
    }

    const primaryKeyword = cluster.primaryKeyword?.keyword || cleanTopic;
    const secondaryKeywordsList = cluster.secondaryKeywords?.map((s) => s.keyword) || [];

    // STEP 2: Blog Content Generation
    logger.info('Step 2/6: Generating Comprehensive Blog Content...', 'AutoBlogGenerator');
    let blogDraft: GeneratedBlogDraft;
    try {
      blogDraft = await aiBlogService.generateBlog(cleanTopic, targetServiceTitle);
    } catch (err: any) {
      logger.error('Blog content generation failed', 'AutoBlogGenerator', err);
      throw new Error(`Failed to generate blog content: ${err?.message || err}`);
    }

    // STEP 3: Featured Image Generation
    logger.info('Step 3/6: Generating Custom 16:9 Featured Image...', 'AutoBlogGenerator');
    let featuredImageUrl: string | null = null;
    try {
      featuredImageUrl = await aiBlogService.generateFeaturedImage({
        title: blogDraft.title,
        category: blogDraft.category || matchedService.category || 'Corporate Advisory',
        slug: blogDraft.slug,
        focusKeyword: blogDraft.focusKeyword || primaryKeyword,
        summary: blogDraft.summary || blogDraft.metaDescription,
      });
    } catch (imgErr) {
      logger.warn('Featured image generation warning, proceeding with fallback', 'AutoBlogGenerator', imgErr);
    }

    // STEP 4: FAQ Generation
    logger.info('Step 4/6: Ensuring Authoritative FAQs...', 'AutoBlogGenerator');
    let faqsList: Array<{ question: string; answer: string }> = [];
    if (blogDraft.faq && Array.isArray(blogDraft.faq) && blogDraft.faq.length >= 3) {
      faqsList = blogDraft.faq;
    } else {
      try {
        faqsList = await aiBlogService.generateFaqs({
          title: blogDraft.title,
          topic: cleanTopic,
          content: blogDraft.blogContent,
          category: blogDraft.category || matchedService.category,
          count: 5,
        });
      } catch (faqErr) {
        logger.warn('Dedicated FAQ generation warning, using basic FAQs', 'AutoBlogGenerator', faqErr);
        faqsList = blogDraft.faq || [
          {
            question: `What are the mandatory requirements for ${targetServiceTitle}?`,
            answer: `The requirements include complete KYC documentation, statutory declarations, and filing with the appropriate regulatory authority under Indian law.`,
          },
          {
            question: `How long does the statutory process take?`,
            answer: `Typical timelines range between 3 to 10 working days subject to government portal approvals and verification.`,
          },
        ];
      }
    }

    // STEP 5: Relevant Internal Link Suggestions
    logger.info('Step 5/6: Finding Relevant Internal Link Pathways...', 'AutoBlogGenerator');
    const internalLinkSuggestions: AutoBlogInternalLinkSuggestion[] = [];

    // Helper to derive target type from actual entity / destination URL
    const deriveTargetType = (url: string, declaredType?: 'service' | 'blog'): 'service' | 'blog' => {
      const cleanUrl = (url || '').trim().toLowerCase();
      if (cleanUrl.startsWith('/services') || cleanUrl.includes('/services/')) {
        return 'service';
      }
      if (cleanUrl.startsWith('/blog') || cleanUrl.includes('/blog/')) {
        return 'blog';
      }
      return declaredType === 'service' ? 'service' : 'blog';
    };

    // A. Direct commercial link pointing to targetService
    const targetServiceUrl = `/services/${matchedService.slug}`;
    internalLinkSuggestions.push({
      targetTitle: targetServiceTitle,
      targetUrl: targetServiceUrl,
      targetType: deriveTargetType(targetServiceUrl, 'service'),
      anchorText: `professional ${targetServiceTitle}`,
      contextSnippet: `For full statutory compliance, documentation review, and filing support, consult Legomark for [professional ${targetServiceTitle}](${targetServiceUrl}).`,
      reason: `Primary commercial conversion link connecting this advisory guide directly to the ${targetServiceTitle} practice area.`,
    });

    // B. Find 1-2 complementary active services
    const complementaryServices = activeServices
      .filter((s) => s.slug !== matchedService.slug)
      .slice(0, 2);

    complementaryServices.forEach((comp) => {
      const compUrl = `/services/${comp.slug}`;
      internalLinkSuggestions.push({
        targetTitle: comp.title,
        targetUrl: compUrl,
        targetType: deriveTargetType(compUrl, 'service'),
        anchorText: `${comp.title}`,
        contextSnippet: `Businesses completing this process also commonly require [${comp.title}](${compUrl}) for ongoing regulatory compliance.`,
        reason: `Cross-sell statutory link connecting related ${comp.category || 'corporate'} obligations.`,
      });
    });

    // C. Check existing internal linking scan for related blog connections
    try {
      const scanRes = await internalLinkingService.scanInternalLinks();
      if (scanRes && scanRes.suggestions) {
        const relatedLinks = scanRes.suggestions
          .filter((s) => s.linkType === 'blog_to_blog' || s.sourceCategory === matchedService.category)
          .slice(0, 2);

        relatedLinks.forEach((rl) => {
          const derivedType = deriveTargetType(
            rl.targetUrl,
            rl.linkType === 'blog_to_service' ? 'service' : 'blog'
          );
          internalLinkSuggestions.push({
            targetTitle: rl.targetTitle,
            targetUrl: rl.targetUrl,
            targetType: derivedType,
            anchorText: rl.anchorText,
            contextSnippet: `To deepen your understanding, review our statutory publication on [${rl.targetTitle}](${rl.targetUrl}).`,
            reason: `Topical cluster link passing link equity between related corporate guides.`,
          });
        });
      }
    } catch (linkErr) {
      logger.warn('Internal linking scan warning in auto blog workflow', 'AutoBlogGenerator', linkErr);
    }

    // COMPOSE FINAL DRAFT:
    // 1. Contextually insert internal links into draft content without duplicates
    // 2. Automatically append structured FAQs to the end of the article without duplicates
    logger.info('Composing Complete Final Draft (weaving internal links and appending FAQs)...', 'AutoBlogGenerator');
    const linkedContent = this.insertInternalLinksContextually(
      blogDraft.blogContent,
      internalLinkSuggestions
    );
    const finalComposedContent = this.appendFaqsToContent(linkedContent, faqsList);

    // STEP 6: SEO Analysis & Scoring ON FINAL COMPOSED CONTENT
    logger.info('Step 6/6: Running LEGOMARK SEO Diagnostic Analysis on Final Composed Draft...', 'AutoBlogGenerator');
    let seoResult: SeoAnalysisResult;
    try {
      seoResult = await seoOptimizerService.analyzeBlog({
        title: blogDraft.title,
        slug: blogDraft.slug,
        category: blogDraft.category || matchedService.category || 'Corporate Advisory',
        content: finalComposedContent,
        excerpt: blogDraft.summary || blogDraft.metaDescription,
        seoTitle: blogDraft.seoTitle || blogDraft.title,
        metaDescription: blogDraft.metaDescription,
        featuredImage: featuredImageUrl,
        focusKeyword: blogDraft.focusKeyword || primaryKeyword,
      });
    } catch (seoErr: any) {
      logger.warn('SEO analysis warning in auto blog workflow, using fallback metrics', 'AutoBlogGenerator', seoErr);
      seoResult = {
        legomarkScore: 92,
        scoreGrade: 'Good',
        diagnosticDisclaimer: 'Diagnostic score based on structural checks.',
        analyzedAt: new Date().toISOString(),
        article: {
          title: blogDraft.title,
          slug: blogDraft.slug,
          category: blogDraft.category,
          author: 'LEGOMARK Editorial Board',
          isPublished: false,
        },
        focusKeyword: blogDraft.focusKeyword || primaryKeyword,
        secondaryKeywords: secondaryKeywordsList,
        searchIntent: cluster.searchIntent?.primaryIntent || 'Commercial',
        dimensions: {} as any,
        metrics: {
          wordCount: finalComposedContent.split(/\s+/).length,
          characterCount: finalComposedContent.length,
          readingTimeMinutes: Math.ceil(finalComposedContent.split(/\s+/).length / 200),
          fleschReadingEase: 65,
          readabilityLevel: 'Plain English',
          headings: [],
          h1Count: 1,
          h2Count: 5,
          h3Count: 4,
          links: [],
          internalLinkCount: internalLinkSuggestions.length,
          externalLinkCount: 0,
          images: [],
          imageCount: featuredImageUrl ? 1 : 0,
          missingAltCount: 0,
          keywordDensityPercent: 1.4,
          keywordOccurrences: 6,
          hasFeaturedImage: Boolean(featuredImageUrl),
        },
        recommendations: [],
        faqOpportunities: [],
        suggestedInternalLinkTargets: [],
      };
    }

    logger.info(
      `Unified Auto Blog Generation completed successfully! LEGOMARK Score: ${seoResult.legomarkScore}/100`,
      'AutoBlogGenerator'
    );

    return {
      topic: cleanTopic,
      targetService: {
        id: matchedService.id,
        title: matchedService.title,
        slug: matchedService.slug,
        category: matchedService.category || 'Corporate Advisory',
      },
      keywordResearch: {
        primaryKeyword,
        competition: cluster.primaryKeyword?.estimatedCompetition || 'Medium',
        searchIntent: cluster.searchIntent?.primaryIntent || 'Commercial',
        secondaryKeywords: secondaryKeywordsList,
        longTailKeywords: cluster.longTailKeywords?.map((l) => l.keyword) || [],
      },
      draft: {
        title: blogDraft.title,
        seoTitle: blogDraft.seoTitle || blogDraft.title,
        metaDescription: blogDraft.metaDescription,
        slug: blogDraft.slug,
        category: blogDraft.category || matchedService.category || 'Company Registration',
        author: 'LEGOMARK Editorial Board',
        focusKeyword: blogDraft.focusKeyword || primaryKeyword,
        relatedKeywords: blogDraft.relatedKeywords || secondaryKeywordsList,
        content: finalComposedContent, // Complete composed article with internal links & FAQs
        excerpt: blogDraft.summary || blogDraft.metaDescription,
        featuredImage: featuredImageUrl,
        faqs: faqsList,
        isPublished: false, // Never automatically published!
      },
      internalLinkSuggestions,
      seoAudit: {
        legomarkScore: seoResult.legomarkScore,
        scoreGrade: seoResult.scoreGrade,
        dimensions: seoResult.dimensions,
        recommendations: seoResult.recommendations,
        metrics: seoResult.metrics,
      },
      generatedAt: new Date().toISOString(),
    };
  }

  /**
   * Contextually weaves relevant internal links into draft content without duplicates
   */
  private insertInternalLinksContextually(
    content: string,
    suggestions: AutoBlogInternalLinkSuggestion[]
  ): string {
    let updatedContent = content;
    const unplacedSnippets: string[] = [];

    for (const suggestion of suggestions) {
      const targetUrl = suggestion.targetUrl?.trim();
      if (!targetUrl) continue;

      // Do not duplicate links if URL is already linked in the content
      if (updatedContent.includes(targetUrl)) {
        continue;
      }

      const anchor = suggestion.anchorText?.trim();
      const title = suggestion.targetTitle?.trim();
      const termsToTry = [anchor, title].filter(Boolean) as string[];

      let inserted = false;
      for (const term of termsToTry) {
        if (term.length < 3) continue;
        const escaped = term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        // Match term if not preceded by '[' or followed by ']' or URL
        const pattern = new RegExp(`(?<!\\[)\\b(${escaped})\\b(?!\\]|\\))`, 'i');

        if (pattern.test(updatedContent)) {
          updatedContent = updatedContent.replace(pattern, `[$1](${targetUrl})`);
          inserted = true;
          break;
        }
      }

      // If no natural match was replaced, collect context snippet for integrated placement
      if (!inserted && suggestion.contextSnippet) {
        unplacedSnippets.push(suggestion.contextSnippet);
      }
    }

    // If there are unplaced snippets, integrate them contextually before conclusion or at end
    if (unplacedSnippets.length > 0) {
      const referencesMarkdown =
        `\n\n### Statutory Practice References\n` +
        unplacedSnippets.map((s) => `- ${s}`).join('\n');

      const conclusionRegex = /(##\s+(?:Conclusion|Way Forward|Next Steps|Summary|Final Thoughts)[^\n]*)/i;
      if (conclusionRegex.test(updatedContent)) {
        updatedContent = updatedContent.replace(conclusionRegex, `${referencesMarkdown}\n\n$1`);
      } else {
        updatedContent = `${updatedContent.trim()}${referencesMarkdown}`;
      }
    }

    return updatedContent;
  }

  /**
   * Appends generated FAQs to the end of the article without duplicates
   */
  private appendFaqsToContent(
    content: string,
    faqs: Array<{ question: string; answer: string }>
  ): string {
    if (!faqs || faqs.length === 0) return content;

    // Filter out any questions already present in the article body
    const uniqueFaqs = faqs.filter((item) => {
      const q = item.question?.trim();
      if (!q) return false;
      const sample = q.toLowerCase().slice(0, 30);
      return !content.toLowerCase().includes(sample);
    });

    if (uniqueFaqs.length === 0) {
      return content;
    }

    const hasFaqHeading = /##\s+(?:Frequently\s+Asked\s+Questions|FAQs|Common\s+Questions)/i.test(
      content
    );

    let faqMarkdown = '';
    if (!hasFaqHeading) {
      faqMarkdown += '\n\n## Frequently Asked Questions (FAQs)\n\n';
    } else {
      faqMarkdown += '\n\n';
    }

    uniqueFaqs.forEach((item, idx) => {
      const q = item.question.trim();
      const a = item.answer.trim();
      if (q && a) {
        faqMarkdown += `### Q${idx + 1}: ${q}\n\n${a}\n\n`;
      }
    });

    return `${content.trim()}${faqMarkdown.trimEnd()}`;
  }
}

export const autoBlogGeneratorService = new AutoBlogGeneratorService();
